### ISSUE TITLE
"-" or "." in n.name property leads to failure of import

### ISSUE THREAD

**Issue by rescuehero** [corwur/cytoscapeneo4j#1]
importing all nodes and edges from neo4j leads to an abort of import and a empty node

if I run following cypher query:
`MATCH (n) RETURN *`
all nodes are returned, even those with "." and "-" in their n.name but the edges are not of course

**Comment by sdijkx** [comment]
The import all nodes and edges used a query that only imported connected nodes, this is changed in release 0.2 .

**Comment by rescuehero** [comment]
is the String now cleared, so you are able to use node.name with "." and "-" in their name?

**Comment by swarris** [comment]
The new release should be able to handle all sorts of strings, including n.name:'hi.'. We did change the functionality of 'import all nodes and edges': this works only for exported networks. If you'd like to import the entire graph (including not connected nodes), use the 'import cypher query' menu option: 
match (n), (m) optional match (n)-[r]-(m) return n,m,r
