### ISSUE TITLE
Problems connecting

### ISSUE THREAD

**Issue by dosumis** [corwur/cytoscapeneo4j#13]
I can't seem to connect to any Neo4J endpoint - I just get connection fails every time.

This endpoint should be credential-less & works fine for REST and bolt connections:

http://pdb.virtualflybrain.org

I've also tried connecting to a local instance on localhost:7474

All fail with the message 'Cannot connect to Neo4j'.  

System:
CytoScape Version: 3.9.0 
Java: 11.0.8 
Mac OS X 10.15.7 - x86_64

Maybe a bug, or am i missing something simple here?

**Comment by swarris** [comment]
Could you check the settings of the database instance? It seems that the port numbers have been altered:
`Server responded HTTP. Make sure you are not trying to connect to the http endpoint (HTTP defaults to port 7474 whereas BOLT defaults to port 7687)`
The other two common ports (7474 and 7473) are not accessible: https://neo4j.com/docs/operations-manual/current/configuration/connectors/
The current implementation requires the bolt interface on port 7687. But the latest source code now support the [neo4j interface.](https://github.com/corwur/cytoscapeneo4j/pull/11)

**Comment by swarris** [comment]
The latest release allows you to select a different port.
