### ISSUE TITLE
exporting does not export the graph as it were when importing

### ISSUE THREAD

**Issue by rescuehero** [corwur/cytoscapeneo4j#2]
expected behaviour:
importing graph, editing some properties, exporting the graph the way it was before with edited properties

actual behaviour:
exported graph has other labels, edges don't have properties but are called LINK now.

**Comment by sdijkx** [comment]
This is a known issue, I will look into it for a next release.

**Comment by rescuehero** [comment]
would be great if it worked :)

Writing a Bachelor-Thesis at the moment in which it would be a nice-to-have feature to add a GUI through cytoscape

**Comment by swarris** [comment]
This has been fixed and will be available in the new release
