### ISSUE TITLE
Connect button is not responsive when using a port number in host name

### ISSUE THREAD

**Issue by lalquier** [corwur/cytoscapeneo4j#4]
Are port numbers other than the default 7474 supported?

The Connect button doesn't do anything I try using the convention 'hostname:port' notation.

**Comment by swarris** [comment]
The default 7474 port number is for HTTP access, usually your browser. The plugin communicates with the neo4j database using the bolt protocol, which usually is available on port number 7687. Giving only the host name should be sufficient, unless your configured neo4j to use another port. The host:port should in that case work.  
If that port is also not available, check you config to see if bolt is enabled:

# Bolt connector
dbms.connector.bolt.enabled=true
#dbms.connector.bolt.tls_level=OPTIONAL
#dbms.connector.bolt.listen_address=:7687

Are you connecting to a server? Please check the config that you allow for connections from other machines than localhost. By default these are not allowed:
# With default configuration Neo4j only accepts local connections.
# To accept non-local connections, uncomment this line:
#dbms.connectors.default_listen_address=0.0.0.0

When your config looks fine, but you still are not able to connect, check your firewall for port 7687.
